"""empty message

Revision ID: a5bc146742fd
Revises: abd44ec7c61f
Create Date: 2022-12-09 18:08:50.239266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5bc146742fd'
down_revision = 'abd44ec7c61f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_pokemon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_caught', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_pokemon', schema=None) as batch_op:
        batch_op.drop_column('date_caught')

    # ### end Alembic commands ###
