"""empty message

Revision ID: abd44ec7c61f
Revises: 
Create Date: 2022-12-09 15:52:31.511176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abd44ec7c61f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('all_pokemon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_shiny', sa.Boolean(), nullable=False))
        batch_op.alter_column('shiny_sprite',
               existing_type=sa.VARCHAR(length=600),
               nullable=True)
        batch_op.drop_column('description')

    with op.batch_alter_table('user_pokemon', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_pokemon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=False))

    with op.batch_alter_table('all_pokemon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.alter_column('shiny_sprite',
               existing_type=sa.VARCHAR(length=600),
               nullable=False)
        batch_op.drop_column('has_shiny')

    # ### end Alembic commands ###
